version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: exp-mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: glossary
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    container_name: exp-mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

  grpc-service:
    build:
      context: ./grpc-app
      dockerfile: Dockerfile
    container_name: exp-grpc-service
    restart: always
    depends_on:
      - mongo
    ports:
      - "50051:50051"

  fastapi-service:
    build:
      context: ./fast-api-app
      dockerfile: Dockerfile
    container_name: exp-fastapi-service
    restart: always
    depends_on:
      - mongo
    ports:
      - "4010:4010"

  load-tests:
    build:
      context: ./load-tests
      dockerfile: Dockerfile
    container_name: exp-load-tests
    restart: always
    depends_on:
      - fastapi-service
      - grpc-service
    ports:
      - "8089:8089"

volumes:
  mongo_data:
